name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: kyoncy/issue-comment-actions@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hey @${{ github.actor }} , Thanks for opening the issue, Someone from our team will soon have a look at your issue and will respond accordingly."
        pr-message: "Hey @${{ github.actor }} , Thanks for contriubuting, Someone from our team will soon review your PR, till then please checkout other issue."
